version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hyper
    versions:
    - 0.14.5
  - dependency-name: simplelog
    versions:
    - 0.10.0
  - dependency-name: anyhow
    versions:
    - 1.0.40
  - dependency-name: thiserror
    versions:
    - 1.0.24
  - dependency-name: reqwest
    versions:
    - 0.11.1
