name: CI

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - run: cargo build --all
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test --all -- --test-threads 1
      - run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out Xml -- --test-threads 1
          bash <(curl -s https://codecov.io/bash)
        if: matrix.os == 'ubuntu-latest'
