name: Publish images

on: [push]

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install qemu
        run: sudo apt install -y qemu binfmt-support qemu-user-static

      - name: podman login
        run: podman login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: podman build
        run: podman build --jobs 4 --platform linux/amd64,linux/arm64 --manifest site24x7_exporter .

      - name: podman manifest push latest
        run: podman manifest push site24x7_exporter docker.io/svenstaro/site24x7_exporter:latest

      - name: podman manifest push tag version
        run: podman manifest push site24x7_exporter docker.io/svenstaro/site24x7_exporter:{{ steps.tag.outputs.current_version }}
        if: startsWith(github.ref, 'refs/tags/v')
